var ../schema/TelemetrySchema={
	"_all":{
		"enabled":false
	},
	"_source":{
		"compress":true
	},
	"properties":{
		"date":{
			"type":"string"
		},
		"measure":{
			"type":"string",
			 "index":"not_analyzed"
		},
		"OS":{
			"type":"string",
			"index":"not_analyzed"
		},
		"appBuildID":{
			"type":"string",
			"index":"not_analyzed"
		},
		"appName":{
			"type":"string",
			"index":"not_analyzed"
		},
		"appUpdateChannel":{
			"type":"string",
			"index":"not_analyzed"
		},
		"appVersion":{
			"type":"string",
			"index":"not_analyzed"
		},
		"arch":{
			"type":"string",
			"index":"not_analyzed"
		},
		"platformBuildID":{
			"type":"string",
			"index":"not_analyzed"
		},
		"reason":{
			"type":"string",
			"index":"not_analyzed"
		},
		"version":{
			"type":"string",
			"index":"not_analyzed"
		},
		"histogram_type":{
			"type":"long",
			"store":"yes",
			"index":"no"
		},
		"bucket_count":{
			"type":"long",
			"store":"yes",
			"index":"no"
		},
		"count":{
			"type":"long",
			"store":"yes",
			"index":"no"
		},
		"range":{
			"type":"long",
			"store":"yes",
			"index":"no"
		},
		"sum":{
			"type":"long",
			"store":"yes",
			"index":"no"
		},
		"values":{
			"type":"long",
			"store":"yes",
			"index":"no"
		}
	}
};

