var MozillaPrograms = {
	"columns":
		["projectName", "attributeName", "attributeValue"],
	"data":[
		["Boot2Gecko (B2G)", "cf_blocking_basecamp", "+"],
		["Security", "status_whiteboard.tokenized", "sg:dos"],
		["Security", "status_whiteboard.tokenized", "sg:low"],
		["Security", "status_whiteboard.tokenized", "sg:mod"],
		["Security", "status_whiteboard.tokenized", "sg:crit"],
		["Security", "keywords", "sec-critical"],
		["Security", "keywords", "sec-moderate"],
		["Security", "keywords", "sec-low"],
		["Security (Critical Only)", "status_whiteboard.tokenized", "sg:crit"],
//		["Security (Critical Only)", "keywords", "sec-high"],
		["Security (Critical Only)", "keywords", "sec-critical"],
		["Security (Critical Only)", "status_whiteboard.tokenized", "sg:crit"],
		["Crash", "keywords", "topcrash"],
		["Crash", "keywords", "crash"],
		["Crash", "keywords", "regression"],
		["Top Crash", "keywords", "topcrash"],
		["QA Wanted", "keywords", "qawanted"],
		["Regression", "status_whiteboard.tokenized", "regression-window-wanted"],
		["Regression", "status_whiteboard.tokenized", "regressionwindow-wanted"],
		["Regression", "keywords", "regressionwindow-wanted"],
		["Snappy", "status_whiteboard.tokenized", "snappy:p1"],
		["Snappy", "status_whiteboard.tokenized", "snappy:p2"],
		["Snappy", "status_whiteboard.tokenized", "snappy:p3"],
		["MemShrink", "status_whiteboard.tokenized", "memshrink:p1"],
		["MemShrink", "status_whiteboard.tokenized", "memshrink:p2"],
		["MemShrink", "status_whiteboard.tokenized", "memshrink:p3"],
//		["Fennec", "flags", "blocking-fennec1.0-beta+"],
		["K9O", "status_whiteboard.tokenized", "k9o:p1"],
		["K9O", "status_whiteboard.tokenized", "k9o:p2"],
		["K9O", "status_whiteboard.tokenized", "k9o:p3"],
		["K9O", "status_whiteboard.tokenized", "k9o:p?"]
	]
};
